scorer: factscore
data_name: tongc-allenai/fact-eval-data
data_split: factscore
model_name_extraction: vllm-openai::meta-llama/Llama-3.1-8B-Instruct
model_name_verification: vllm-openai::meta-llama/Llama-3.1-8B-Instruct
search_model_name: bm25-only
search_chunk_size: 100
search_num_chunks: 10
search_num_processes: 1
length_penalty_threshold: 10
max_samples: 100
batch_size: 256